# Jekyll
permalink: /:year/:title/
paginate: 5
exclude: []
name: Notes on Computer Vision
baseurl: null

#
github_username:  shicai
twitter_username: shicai
weibo_username: shicaiyang

markdown: kramdown
